apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-devops-dashboard
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: aws-dashboard.k.elidev.info
    http:
      paths:
      - backend:
          service:
            name: aws-devops-dashboard
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - aws-dashboard.k.elidev.info
    secretName: aws-dashboard.k.elidev.info
