apiVersion: v1
kind: Secret
metadata:
  name: aws-devops-dashboard-secrets
  namespace: default
type: Opaque
stringData:
  PASSWORD_LOGIN: ${PASSWORD_LOGIN}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
